# Development override for docker-compose.yml
version: '3.8'

services:
  expense-sage-web:
    build:
      target: build  # Use build stage for development
    ports:
      - "3000:80"    # Different port for development
    volumes:
      - .:/app       # Mount source code for hot reload
      - /app/build   # Exclude build directory
    environment:
      - NODE_ENV=development
      - FLUTTER_WEB_USE_SKIA=true
    command: >
      sh -c "
        flutter pub get &&
        flutter build web --debug &&
        nginx -g 'daemon off;'
      "

  expense-sage-db:
    ports:
      - "5432:5432"  # Expose database port for development

  # Development tools
  expense-sage-dev:
    build:
      context: .
      target: build
    container_name: expense-sage-dev
    volumes:
      - .:/app
      - flutter_cache:/root/.flutter
    working_dir: /app
    command: >
      sh -c "
        flutter pub get &&
        flutter analyze &&
        flutter test &&
        tail -f /dev/null
      "
    networks:
      - expense-sage-network
    profiles:
      - development

volumes:
  flutter_cache:
